export interface Studio {
  name: string;
  code: string;
  owner: string;
}

export interface Agency {
  name: string;
  id: string;
}

export const STUDIOS: Studio[] = [
  { name: "Fort Lauderdale, FL", code: "FL026", owner: "Lisa Schiller & Tom Francella" },
  { name: "West Caldwell, NJ", code: "NJ060", owner: "Richard Uku & Kareem Holligan" },
  { name: "Bellingham, WA", code: "WA049", owner: "Kristin & Joshua Clarkman" },
  { name: "Port Chester, NY", code: "NY045", owner: "Dan Weinstein & Erik Geisler" },
  { name: "Lake Pleasant, AZ", code: "AZ027", owner: "James Robb" },
  { name: "Windsong Ranch, TX", code: "TX126", owner: "Hareesh Veldandi" },
  { name: "East Greenwich, RI", code: "RI004", owner: "Shannon McLaughlin" },
  { name: "Eugene, OR", code: "OR010", owner: "Trevor Wichmann & Bill Pierznik" },
  { name: "Shrewsbury, NJ", code: "NJ039", owner: "Steve Chaloult" },
  { name: "College Station, TX", code: "TX112", owner: "Katy Lee" },
  { name: "Fairlawn, OH", code: "OH027", owner: "Kurt Altenburger" },
  { name: "Plantation, FL", code: "FL039", owner: "Kim Weiss" },
  { name: "Bluffton, SC", code: "SC024", owner: "Dan Lieberman" },
  { name: "Glastonbury, CT", code: "CT017", owner: "Andy Sale" },
  { name: "Pembroke Pines, FL", code: "FL087", owner: "Kim Weiss" },
  { name: "Nona, FL", code: "FL107", owner: "Kal Gullapalli" },
  { name: "Portsmouth - South, NH", code: "NH005", owner: "Dwayne Duprey" },
  { name: "Rock Hill, SC", code: "SC013", owner: "Mike & Sara O'Kelly" },
  { name: "Pittsford, NY", code: "NY065", owner: "Tom Kanyok" },
  { name: "Reno Northwest, NV", code: "NV009", owner: "Ilan Frank" },
  { name: "Fleming Island, FL", code: "FL054", owner: "Eric & Anna Kehle" },
  { name: "Scarsdale, NY", code: "NY069", owner: "Jeremy Hirsch, Erik Geisler, Dan Weinstein" },
  { name: "Woodstock, GA", code: "GA009", owner: "Ali Korf" },
  { name: "North Naples, FL", code: "FL108", owner: "Nic Christiano" },
  { name: "Chicago - Lincoln Park, IL", code: "IL017", owner: "Scott Weinstein" },
  { name: "Marina Del Ray, CA", code: "CA016", owner: "Ilan Frank" },
  { name: "Brooklyn - Williamsburg, NY", code: "NY008", owner: "Jeremy Hirsch, Erik Geisler, Dan Weinstein" },
  { name: "Chino Hills, CA", code: "CA077", owner: "Parag Laddha" },
  { name: "Somerville, MA", code: "MA014", owner: "Parag Laddha" },
  { name: "Cherry Hills, CO", code: "CO033", owner: "Daniel & Chelsey Franklin" },
  { name: "Santa Barbara, CA", code: "CA120", owner: "Brandon Cox" },
  { name: "Irvine, CA", code: "CA013", owner: "Marc Thomas" },
  { name: "Clearwater, FL", code: "FL082", owner: "Grant Heller" },
  { name: "Nashua, NH", code: "NH002", owner: "Dwayne Duprey" },
  { name: "League City, TX", code: "TX048", owner: "Jerome Carter" },
  { name: "Westbury, NY", code: "NY025", owner: "Level 5 - Be Well" },
  { name: "Charlotte, NC", code: "NC001", owner: "Kyler Ferguson" },
  { name: "Virginia Beach, VA", code: "VA001", owner: "Lenys Alcoreza" },
  { name: "Sugar House, UT", code: "UT001", owner: "Clint Peck" },
  { name: "Southpark, NC", code: "NC002", owner: "Kyler Ferguson" },
  { name: "Sonterra, TX", code: "TX008", owner: "Brittany Kolkhorst" },
  { name: "Draper, UT", code: "UT002", owner: "Clint Peck" },
  { name: "Lake Oswego, OR", code: "OR001", owner: "Chris and Anika Warden" },
  { name: "Lubbock, TX", code: "TX009", owner: "Laura Smith" },
  { name: "Tigard, OR", code: "OR002", owner: "Meraki" },
  { name: "Marlton, NJ", code: "NJ001", owner: "Sue Simonetti" },
  { name: "Kirkland, WA", code: "WA001", owner: "Dannelle (DJ) Carlson" },
  { name: "Laguna, CA", code: "CA001", owner: "Marc Thomas" },
  { name: "RVA GreenGate, VA", code: "VA002", owner: "Niraj Patel" },
  { name: "Issaquah, WA", code: "WA002", owner: "Dannelle (DJ) Carlson" },
  { name: "Station Park, UT", code: "UT003", owner: "Clint Peck" },
  { name: "S Chandler, AZ", code: "AZ003", owner: "Level 5 - Be Well" },
  { name: "Tempe, AZ", code: "AZ004", owner: "Level 5 - Be Well" },
  { name: "Cedar Mill, OR", code: "OR003", owner: "Meraki" },
  { name: "Rea Farms, NC", code: "NC006", owner: "Kyler Ferguson" },
  { name: "Norterra, AZ", code: "AZ013", owner: "Level 5 - Be Well" },
  { name: "Arrowhead, AZ", code: "AZ026", owner: "Level 5 - Be Well" },
  { name: "Mountain Brook, AL", code: "AL001", owner: "Steve Olson" },
  { name: "Gainey Village, AZ", code: "AZ006", owner: "Level 5 - Be Well" },
  { name: "Mt Juliet, TN", code: "TN008", owner: "Brett Wade" },
  { name: "Riverton, UT", code: "UT008", owner: "Meraki" },
  { name: "The Quarry, TX", code: "TX021", owner: "Brittany Kolkhorst" },
  { name: "Frisco, TX", code: "TX011", owner: "Laura Smith" },
  { name: "Raleigh, NC", code: "NC005", owner: "Meri Clark" },
  { name: "Cottonwoodheights, UT", code: "UT006", owner: "Meraki" },
  { name: "Maple Grove, MN", code: "MN003", owner: "Perry Rice" },
  { name: "U-Village, WA", code: "WA017", owner: "Meraki" },
  { name: "Alexandria, VA", code: "VA045", owner: "Level 5 - Be Well" },
  { name: "San Diego La Costa, CA", code: "CA126", owner: "Marc Thomas" },
  { name: "Dunwoody, GA", code: "GA028", owner: "Level 5 - Be Well" },
  { name: "Redondo Beach, CA", code: "CA113", owner: "Michelle Kelly" },
  { name: "San Diego Del Mar, CA", code: "CA006", owner: "Marc Thomas" },
  { name: "Westlake Village, CA", code: "CA102", owner: "Brandon Cox" },
  { name: "Durham, NC", code: "NC016", owner: "Meri Clark" },
  { name: "Santa Clarita, CA", code: "CA159", owner: "Parag Laddha" },
  { name: "Norfolk, VA", code: "VA035", owner: "Lenys Alcoreza" },
  { name: "Happy Valley, OR", code: "OR013", owner: "Chris and Anika Warden" },
  { name: "Santa Fe, NM", code: "NM002", owner: "Elizabeth Lutes" },
  { name: "West Village, TX", code: "TX025", owner: "Gabby Pollock" },
  { name: "Ventura Place, NM", code: "NM003", owner: "Elizabeth Lutes" },
  { name: "Allen, TX", code: "TX062", owner: "Level 5 - Be Well" },
  { name: "Baltimore, MD", code: "MD011", owner: "Lenys Alcoreza" },
  { name: "Los Gatos, CA", code: "CA002", owner: "Becky Keady" },
  { name: "Tustin, CA", code: "CA005", owner: "Marc Thomas" },
  { name: "Pentagon City, VA", code: "VA017", owner: "Level 5 - Be Well" },
  { name: "Midlothian, VA", code: "VA013", owner: "Niraj Patel" },
  { name: "Chapel Hill, NC", code: "NC007", owner: "Meri Clark" },
  { name: "Minnetonka, MN", code: "MN011", owner: "Perry Rice" },
  { name: "La Jolla, CA", code: "CA135", owner: "Marc Thomas" },
  { name: "Cerritos, CA", code: "CA078", owner: "Parag Laddha" },
  { name: "Tanglewood, TX", code: "TX073", owner: "Level 5 - Be Well" },
  { name: "Mission Viejo, CA", code: "CA174", owner: "Marc Thomas" },
  { name: "Morristown, NJ", code: "NJ012", owner: "Steve Chaloult" },
  { name: "Newport Beach, CA", code: "CA142", owner: "Marc Thomas" },
  { name: "Point Loma, CA", code: "CA119", owner: "Marc Thomas" },
  { name: "Edgewater, NJ", code: "NJ021", owner: "Level 5 - Be Well" },
  { name: "Plano, TX", code: "TX005", owner: "Jeff Kampinga" },
  { name: "Austin - Gateway, TX", code: "TX006", owner: "Rudy Meijia" },
  { name: "Lancaster, PA", code: "PA001", owner: "Andy Ayers" },
  { name: "Columbus, OH", code: "OH001", owner: "Dan Rogovin" },
  { name: "Pittsburgh, PA", code: "PA002", owner: "Dana Donaldson" },
  { name: "Westlake, OH", code: "OH002", owner: "Kurt Altenburger" },
  { name: "Plymouth, PA", code: "PA003", owner: "Andy Ayers" },
  { name: "Perrysburg, OH", code: "OH003", owner: "John & Victoria Fellhauer" },
  { name: "Katy, TX", code: "TX014", owner: "Brian Haden" },
  { name: "Vinings, GA", code: "GA004", owner: "Ali Korf" },
  { name: "Sacramento, CA", code: "CA003", owner: "Ilan Frank" },
  { name: "Ann Arbor, MI", code: "MI001", owner: "Daniel Graves" },
  { name: "Hyde Park, OH", code: "OH004", owner: "John Fox" },
  { name: "West Side Village, GA", code: "GA003", owner: "Eric Cain" },
  { name: "Lovers Lane, TX", code: "TX018", owner: "Jim Donnelly" },
  { name: "Carmel, IN", code: "IN001", owner: "Heather Mesalam" },
  { name: "Preston Forest, TX", code: "TX099", owner: "Jim Donnelly" },
  { name: "Strongsville, OH", code: "OH020", owner: "Kurt Altenburger" },
  { name: "Southlake, TX", code: "TX019", owner: "Josh Dennis" },
  { name: "West University, TX", code: "TX012", owner: "Dennis Tran" },
  { name: "Dublin, OH", code: "OH005", owner: "Dan Rogovin" },
  { name: "Cedar Park, TX", code: "TX075", owner: "Sarah Milliken & Julia Rhie" },
  { name: "South Lamar, TX", code: "TX024", owner: "Rudy Meijia" },
  { name: "Westlake, TX", code: "TX091", owner: "David Wimberly" },
  { name: "Colleyville, TX", code: "TX095", owner: "Josh Dennis" },
  { name: "Paoli, PA", code: "PA007", owner: "Andy Ayers" },
  { name: "Shadyside, PA", code: "PA006", owner: "Tommy McCafferty" },
  { name: "Fishers, IN", code: "IN003", owner: "Heather Mesalam" },
  { name: "Woodmere, OH", code: "OH010", owner: "Kurt Altenburger" },
  { name: "BCS, TX", code: "TX111", owner: "Katy Lee" },
  { name: "Brownsboro, KY", code: "KY004", owner: "John Fox" },
  { name: "Roseville Fountains, CA", code: "CA022", owner: "Ilan Frank" },
  { name: "Collegeville, PA", code: "PA011", owner: "Andy Ayers" },
  { name: "Murphy, TX", code: "TX046", owner: "Shane & Priscilla Land" },
  { name: "Media, PA", code: "PA016", owner: "Andy Ayers" },
  { name: "Cranberry Township, PA", code: "PA020", owner: "Tom Kanyok" },
  { name: "Zionsville, IN", code: "IN005", owner: "Heather Mesalam" },
  { name: "Beavercreek, OH", code: "OH007", owner: "John Fox" },
  { name: "Folsom, CA", code: "CA148", owner: "Ilan Frank" },
  { name: "McCandless, PA", code: "PA021", owner: "Tom Kanyok" },
  { name: "The Woodlands, TX", code: "TX020", owner: "Jill Loya" },
  { name: "Exton, PA", code: "PA005", owner: "Andy Ayers" },
  { name: "Bedford, NH", code: "NH001", owner: "Stacy DeJesus" },
  { name: "Woburn, MA", code: "MA009", owner: "Parag Laddha" },
  { name: "Buford, GA", code: "GA020", owner: "Jose Cherres" },
  { name: "Portsmouth, NH", code: "NH006", owner: "Dwayne Duprey" },
  { name: "Lawrenceville, NJ", code: "NJ002", owner: "Steve Chaloult" },
  { name: "North McKinney, TX", code: "TX016", owner: "Jim Donnelly" },
  { name: "Richardson, TX", code: "TX049", owner: "Jim Donnelly" },
  { name: "Warrington, PA", code: "PA009", owner: "Andy Ayers" },
  { name: "San Antonio, TX", code: "TX076", owner: "Dana Bednorz" },
  { name: "City Center, PA", code: "PA019", owner: "Andy Ayers" },
  { name: "Santa Monica, CA", code: "CA025", owner: "Ilan Frank" },
  { name: "West Palm Beach, FL", code: "FL008", owner: "Kim Weiss" },
  { name: "Vienna, VA", code: "VA026", owner: "Level 5 - Be Well" },
  { name: "Midtown - ATL, GA", code: "GA038", owner: "Level 5 - Be Well" },
  { name: "Arbor Trails, TX", code: "TX001", owner: "Corporate" },
  { name: "Sugar Land, TX", code: "TX004", owner: "Brian Haden" },
  { name: "Sandy Springs, GA", code: "GA001", owner: "Corporate" },
  { name: "Woodbury, MN", code: "MN001", owner: "Perry Rice" },
  { name: "West Ashley, SC", code: "SC001", owner: "Dan Lieberman" },
  { name: "Boca Raton, FL", code: "FL001", owner: "Kim Weiss" },
  { name: "West Delray, FL", code: "FL002", owner: "Kim Weiss" },
  { name: "Highlands Ranch, CO", code: "CO001", owner: "Kirk Mickelsen" },
  { name: "Hilton Head, SC", code: "SC002", owner: "Dan Lieberman" },
  { name: "St Petersburg, FL", code: "FL004", owner: "Nic Christiano" },
  { name: "North Scottsdale, AZ", code: "AZ001", owner: "Corporate" },
  { name: "Lake Mary, FL", code: "FL003", owner: "Daneen Foxwell" },
  { name: "Mueller, TX", code: "TX010", owner: "Corporate" },
  { name: "Greenville, SC", code: "SC003", owner: "Tricia Craddock" },
  { name: "Carrollwood, FL", code: "FL009", owner: "Roisin & John Magee" },
  { name: "Meridian, ID", code: "ID001", owner: "Tim Jolicoeur" },
  { name: "Pinecrest, FL", code: "FL005", owner: "Corporate" },
  { name: "Deerfield, IL", code: "IL001", owner: "Scott Weinstein" },
  { name: "Northbrook, IL", code: "IL002", owner: "Scott Weinstein" },
  { name: "Orlando, FL", code: "FL010", owner: "Kal Gullapalli" },
  { name: "Naples, FL", code: "FL007", owner: "Nic Christiano" },
  { name: "Westchase, FL", code: "FL012", owner: "Roisin & John Magee" },
  { name: "Bethesda, MD", code: "MD002", owner: "Corporate" },
  { name: "Avalon, GA", code: "GA002", owner: "Jose Cherres" },
  { name: "Evanston, IL", code: "IL003", owner: "Scott Weinstein" },
  { name: "Jacksonville Beach, FL", code: "FL006", owner: "Eric & Anna Kehle" },
  { name: "Palm Beach Gardens, FL", code: "FL013", owner: "Kim Weiss" },
  { name: "SoBo, CO", code: "CO003", owner: "Tony Omran" },
  { name: "Boulder, CO", code: "CO006", owner: "Brian Uhlmer & Stephanie Peterson" },
  { name: "East Boise, ID", code: "ID005", owner: "Tim Jolicoeur" },
  { name: "Cherry Creek, CO", code: "CO010", owner: "Daniel & Chelsey Franklin" },
  { name: "Sarasota UTC, FL", code: "FL060", owner: "Nic Christiano" },
  { name: "Tennyson, CO", code: "CO048", owner: "Meraki" },
  { name: "Winter Park, FL", code: "FL016", owner: "Kal Gullapalli" },
  { name: "Colorado Springs, CO", code: "CO023", owner: "Meraki" },
  { name: "Blaine, MN", code: "MN005", owner: "Tram Holloway" },
  { name: "Central Park, CO", code: "CO038", owner: "Meraki" },
  { name: "North Mount Pleasant, SC", code: "SC012", owner: "Dan Lieberman" },
  { name: "Oakbrook Terrace, IL", code: "IL023", owner: "Scott Weinstein" },
  { name: "Applewood, CO", code: "CO027", owner: "Shawn Johnson" },
  { name: "West Loop, IL", code: "IL011", owner: "Scott Weinstein" },
  { name: "Peach Tree City, GA", code: "GA019", owner: "Corporate" },
  { name: "Littleton, CO", code: "CO014", owner: "Kirk Mickelsen" },
  { name: "South Mount Pleasant, SC", code: "SC004", owner: "Dan Lieberman" },
  { name: "Four Points, TX", code: "TX108", owner: "Sarah Milliken & Julia Rhie" },
  { name: "Brambleton, VA", code: "VA003", owner: "John, Kirk, & Justin Galiani" },
  { name: "Rockville, MD", code: "MD019", owner: "John, Kirk, & Justin Galiani" },
  { name: "River Oaks, TX", code: "TX007", owner: "Corporate" },
  { name: "Torrance, CA", code: "CA116", owner: "Parag Laddha" },
  { name: "Upper Arlington, OH", code: "OH038", owner: "Dan Rogovin" },
  { name: "Baybrook, TX", code: "TX027", owner: "Jerome Carter" },
  { name: "Brentwood, TN", code: "TN001", owner: "Tara Magnarini" },
  { name: "Chesterfield, MO", code: "MO001", owner: "Jason Miltenberger" },
  { name: "Oklahoma City, OK", code: "OK001", owner: "Jason Miltenberger" },
  { name: "Henderson, NV", code: "NV001", owner: "Tim Jolicoeur" },
  { name: "South Tulsa, OK", code: "OK002", owner: "Jason Miltenberger" },
  { name: "Green Hills, TN", code: "TN002", owner: "Tara Magnarini" },
  { name: "Murfreesboro, TN", code: "TN018", owner: "Gabe Beukinga" },
  { name: "Lynnfield, MA", code: "MA004", owner: "Parag Laddha" },
  { name: "Summerlin South, NV", code: "NV010", owner: "Tim Jolicoeur" },
  { name: "Apple Valley, MN", code: "MN004", owner: "Perry Rice" },
  { name: "Brooklyn - Park Slope, NY", code: "NY010", owner: "Jeremy Hirsch, Erik Geisler, Dan Weinstein" },
  { name: "Pleasant Hill, CA", code: "CA053", owner: "Ilan Frank" },
  { name: "Westport, CT", code: "CT001", owner: "Andy Sale" },
  { name: "Little Rock, AR", code: "AR001", owner: "Andrew Roy" },
  { name: "Rogers, AR", code: "AR002", owner: "Doug Sperber" },
  { name: "Stamford, CT", code: "CT002", owner: "Andy Sale" },
  { name: "Woodbury, NY", code: "NY001", owner: "Andy Sale" },
  { name: "Wichita, KS", code: "KS001", owner: "Andrew Roy" },
  { name: "Newton, MA", code: "MA003", owner: "Mandy Oberton" },
  { name: "Olathe, KS", code: "KS002", owner: "Andrew Roy" },
  { name: "Hingham, MA", code: "MA001", owner: "Mandy Oberton" },
  { name: "West Hartford, CT", code: "CT015", owner: "Andy Sale" },
  { name: "Overland Park, KS", code: "KS004", owner: "Andrew Roy" },
  { name: "West Omaha, NE", code: "NE001", owner: "Andrew Roy" },
  { name: "Wilderness Hills, NE", code: "NE006", owner: "Wes Heiser" },
  { name: "South Portland, ME", code: "ME001", owner: "Steve & Katie Woods" },
  { name: "El Paso, TX", code: "TX079", owner: "Jose and Blanca Alcoreza" },
  { name: "Barley Mill, DE", code: "DE002", owner: "Andy Ayers" },
  { name: "Meyerland, TX", code: "TX071", owner: "Level 5 - Be Well" },
  { name: "UES 84th St., NY", code: "NY030", owner: "Corporate" },
  { name: "Watertown, MA", code: "MA012", owner: "Parag Laddha" },
  { name: "Crestview Hills, KY", code: "KY007", owner: "John Fox" },
  { name: "Goodyear, AZ", code: "AZ019", owner: "Corporate" },
  { name: "Seminole, FL", code: "FL080", owner: "Grant Heller" },
  { name: "Mt Kisco, NY", code: "NY006", owner: "Jeremy Hirsch, Erik Geisler, Dan Weinstein" },
  { name: "Elmwood, LA", code: "LA003", owner: "Corporate" },
  { name: "Mandeville, LA", code: "LA006", owner: "Corporate" },
  { name: "Morrisville, NC", code: "NC020", owner: "Thomas & Leslie-Anne Ball, Kathryn MacKinnon" },
  { name: "Zona Rosa, MO", code: "MO014", owner: "Scott Lowe" },
  { name: "Live Oak, TX", code: "TX077", owner: "Corporate" },
  { name: "Bozeman, MT", code: "MT001", owner: "Doug Sperber" },
  { name: "Birmingham, MI", code: "MI003", owner: "Scott Marcus" },
  { name: "Royal Oak, MI", code: "MI027", owner: "Scott Marcus" },
  { name: "Billings, MT", code: "MT002", owner: "Doug Sperber" },
  { name: "Dedham, MA", code: "MA002", owner: "Shannon McLaughlin" },
  { name: "Northville, MI", code: "MI002", owner: "Scott Marcus" },
  { name: "Nashville - Music Row, TN", code: "TN004", owner: "Gabe Beukinga" },
  { name: "Cranston, RI", code: "RI001", owner: "Shannon McLaughlin" },
  { name: "Paramus, NJ", code: "NJ018", owner: "Level 5 - Be Well" },
  { name: "Las Colinas, TX", code: "TX053", owner: "Level 5 - Be Well" },
  { name: "Palm Desert, CA", code: "CA156", owner: "Will & Kathryn Norris" },
  { name: "Estero, FL", code: "FL047", owner: "Nic Christiano" },
  { name: "UWS 76th, NY", code: "NY031", owner: "Corporate" },
  { name: "New York, NY", code: "NY002", owner: "Corporate" },
  { name: "Chelsea, NY", code: "NY003", owner: "Corporate" },
  { name: "Erie, CO", code: "CO050", owner: "Brian Uhlmer & Stephanie Peterson" },
  { name: "Austin Triangle, TX", code: "TX107", owner: "David Fossas" },
  { name: "Round Rock, TX", code: "TX002", owner: "Joe Van" },
  { name: "Bee Cave, TX", code: "TX003", owner: "David Wimberly" },
  { name: "Searcy, AR", code: "AR003", owner: "Wesley Griffin" },
  { name: "Durango, CO", code: "CO004", owner: "Elizabeth Lutes" },
  { name: "Smyrna, TN", code: "TN020", owner: "Brandon Butterfield" },
];

export const SERVICE_GROUPS = [
  "core",
  "skin-health",
  "medical",
  "weight-loss",
  "iv-drip",
];

export const AGENCIES: Agency[] = [
  { name: "Digital Tank", id: "DTMA" },
  { name: "FUEL", id: "FUEL" },
  { name: "Redefined Growth Marketing", id: "RGM" },
  { name: "Level 5 / Be Well", id: "L5" },
  { name: "Kathryn MacKinnon Business", id: "KMB" },
  { name: "Angela", id: "Angela" },
  { name: "Patient Engine", id: "PE" },
  { name: "Franchise Ramp", id: "FR" },
  { name: "Distruptive Digital (fran)", id: "DD - fran" },
  { name: "Distruptive Digital (corp)", id: "DD - corp" },
  { name: "KSAR", id: "KSAR" },
  { name: "ROR", id: "ROR" },
  { name: "Andrew", id: "Andrew" },
];

export const FRANCHISE_OWNERS = [
  "Ali Korf",
  "Andrew Roy",
  "Andy Ayers",
  "Andy Sale",
  "Becky Keady",
  "Brandon Cox",
  "Brett Wade",
  "Brian Haden",
  "Brian Uhlmer & Stephanie Peterson",
  "Brittany Kolkhorst",
  "Chris and Anika Warden",
  "Clint Peck",
  "Corporate",
  "Dan Lieberman",
  "Dan Rogovin",
  "Dan Weinstein & Erik Geisler",
  "Dana Bednorz",
  "Dana Donaldson",
  "Daniel & Chelsey Franklin",
  "Daniel Graves",
  "Dannelle (DJ) Carlson",
  "David Fossas",
  "David Wimberly",
  "Dennis Tran",
  "Doug Sperber",
  "Dwayne Duprey",
  "Elizabeth Lutes",
  "Eric & Anna Kehle",
  "Eric Cain",
  "Gabby Pollock",
  "Gabe Beukinga",
  "Grant Heller",
  "Hareesh Veldandi",
  "Heather Mesalam",
  "Ilan Frank",
  "James Robb",
  "Jason Miltenberger",
  "Jeff Kampinga",
  "Jeremy Hirsch, Erik Geisler, Dan Weinstein",
  "Jerome Carter",
  "Jill Loya",
  "Jim Donnelly",
  "Joe Van",
  "John & Victoria Fellhauer",
  "John Fox",
  "John, Kirk, & Justin Galiani",
  "Jose and Blanca Alcoreza",
  "Jose Cherres",
  "Josh Dennis",
  "Kal Gullapalli",
  "Katy Lee",
  "Kim Weiss",
  "Kirk Mickelsen",
  "Kristin & Joshua Clarkman",
  "Kurt Altenburger",
  "Kyler Ferguson",
  "Laura Smith",
  "Lenys Alcoreza",
  "Level 5 - Be Well",
  "Lisa Schiller & Tom Francella",
  "Mandy Oberton",
  "Marc Thomas",
  "Meraki",
  "Michelle Kelly",
  "Mike & Sara O'Kelly",
  "Nic Christiano",
  "Niraj Patel",
  "Parag Laddha",
  "Perry Rice",
  "Richard Uku & Kareem Holligan",
  "Roisin & John Magee",
  "Rudy Meijia",
  "Sarah Milliken & Julia Rhie",
  "Scott Lowe",
  "Scott Marcus",
  "Scott Weinstein",
  "Shane & Priscilla Land",
  "Shannon McLaughlin",
  "Shawn Johnson",
  "Stacy DeJesus",
  "Steve & Katie Woods",
  "Steve Chaloult",
  "Steve Olson",
  "Sue Simonetti",
  "Tara Magnarini",
  "Thomas & Leslie-Anne Ball, Kathryn MacKinnon",
  "Tim Jolicoeur",
  "Tom Kanyok",
  "Tommy McCafferty",
  "Tram Holloway",
  "Trevor Wichmann & Bill Pierznik",
  "Wes Heiser",
  "Wesley Griffin",
  "Will & Kathryn Norris"
].sort();
