export interface Studio {
  name: string;
  code: string;
}

export interface Agency {
  name: string;
  id: string;
}

export const STUDIOS: Studio[] = [
  { name: "Birmingham, AL - Mountain Brook", code: "AL001" },
  { name: "Rogers, AR", code: "AR002" },
  { name: "Phoenix, AZ - North Scottsdale", code: "AZ001" },
  { name: "Chandler, AZ - South", code: "AZ003" },
  { name: "Scottsdale, AZ - Gainey Village", code: "AZ006" },
  { name: "Phoenix, AZ - Norterra", code: "AZ013" },
  { name: "Goodyear, AZ", code: "AZ019" },
  { name: "Peoria, AZ - Lake Pleasant", code: "AZ027" },
  { name: "Laguna Niguel, CA", code: "CA001" },
  { name: "Los Gatos, CA", code: "CA002" },
  { name: "Sacramento, CA - Loehmann's Plaza", code: "CA003" },
  { name: "Tustin, CA", code: "CA005" },
  { name: "Marina Del Rey, CA", code: "CA016" },
  { name: "Roseville, CA", code: "CA022" },
  { name: "Santa Monica, CA", code: "CA025" },
  { name: "Pleasant Hill, CA", code: "CA053" },
  { name: "Chino Hills, CA", code: "CA077" },
  { name: "Cerritos, CA", code: "CA078" },
  { name: "Westlake Village, CA", code: "CA102" },
  { name: "Redondo Beach, CA", code: "CA113" },
  { name: "Torrance, CA", code: "CA116" },
  { name: "Santa Barbara, CA", code: "CA120" },
  { name: "Folsom, CA", code: "CA148" },
  { name: "Palm Desert, CA", code: "CA156" },
  { name: "Santa Clarita, CA", code: "CA159" },
  { name: "Mission Viejo, CA", code: "CA174" },
  { name: "Boulder, CO", code: "CO006" },
  { name: "Wheat Ridge, CO - Applewood", code: "CO027" },
  { name: "Denver, CO - Cherry Hills", code: "CO033" },
  { name: "Erie, CO", code: "CO050" },
  { name: "Westport, CT", code: "CT001" },
  { name: "Stamford, CT", code: "CT002" },
  { name: "West Hartford, CT", code: "CT015" },
  { name: "Glastonbury, CT", code: "CT017" },
  { name: "Greenville, DE - Barley Mill", code: "DE002" },
  { name: "Boca Raton, FL", code: "FL001" },
  { name: "Delray Beach, FL", code: "FL002" },
  { name: "Lake Mary, FL", code: "FL003" },
  { name: "St. Petersburg, FL", code: "FL004" },
  { name: "Pinecrest, FL", code: "FL005" },
  { name: "Jacksonville Beach, FL", code: "FL006" },
  { name: "Naples, FL", code: "FL007" },
  { name: "West Palm Beach, FL", code: "FL008" },
  { name: "Tampa, FL - Carrollwood", code: "FL009" },
  { name: "Orlando, FL - Dr. Phillips", code: "FL010" },
  { name: "Tampa, FL - Westchase", code: "FL012" },
  { name: "Palm Beach Gardens, FL", code: "FL013" },
  { name: "Winter Park, FL", code: "FL016" },
  { name: "Plantation, FL", code: "FL039" },
  { name: "Estero, FL", code: "FL047" },
  { name: "Fleming Island, FL", code: "FL054" },
  { name: "Sarasota, FL - University Park", code: "FL060" },
  { name: "Seminole, FL", code: "FL080" },
  { name: "Clearwater, FL", code: "FL082" },
  { name: "Pembroke Pines, FL", code: "FL087" },
  { name: "Orlando, FL - Nona", code: "FL107" },
  { name: "North Naples, FL", code: "FL108" },
  { name: "Alpharetta, GA", code: "GA002" },
  { name: "Atlanta, GA - Westside Village", code: "GA003" },
  { name: "Atlanta, GA - Vinings", code: "GA004" },
  { name: "Woodstock, GA", code: "GA009" },
  { name: "Peachtree City, GA", code: "GA019" },
  { name: "Buford, GA", code: "GA020" },
  { name: "Dunwoody, GA - Perimeter", code: "GA028" },
  { name: "Atlanta, GA - Midtown", code: "GA038" },
  { name: "Meridian, ID", code: "ID001" },
  { name: "Boise, ID - Bown Crossing", code: "ID005" },
  { name: "Deerfield, IL", code: "IL001" },
  { name: "Northbrook, IL", code: "IL002" },
  { name: "Evanston, IL", code: "IL003" },
  { name: "Chicago, IL - West Loop", code: "IL011" },
  { name: "Chicago, IL - Lincoln Park", code: "IL017" },
  { name: "Oakbrook Terrace, IL", code: "IL023" },
  { name: "Carmel, IN", code: "IN001" },
  { name: "Fishers, IN", code: "IN003" },
  { name: "Zionsville, IN", code: "IN005" },
  { name: "Wichita, KS - East", code: "KS001" },
  { name: "Overland Park, KS", code: "KS004" },
  { name: "Louisville, KY - Brownsboro", code: "KY004" },
  { name: "Crestview Hills, KY", code: "KY007" },
  { name: "Elmwood, LA", code: "LA003" },
  { name: "Mandeville, LA", code: "LA006" },
  { name: "Hingham, MA", code: "MA001" },
  { name: "Dedham, MA", code: "MA002" },
  { name: "Newton, MA", code: "MA003" },
  { name: "Lynnfield, MA", code: "MA004" },
  { name: "Somerville, MA", code: "MA014" },
  { name: "Baltimore, MD - Canton", code: "MD011" },
  { name: "Rockville, MD", code: "MD019" },
  { name: "South Portland, ME", code: "ME001" },
  { name: "Ann Arbor, MI", code: "MI001" },
  { name: "Northville, MI", code: "MI002" },
  { name: "Birmingham, MI", code: "MI003" },
  { name: "Woodbury, MN", code: "MN001" },
  { name: "Maple Grove, MN", code: "MN003" },
  { name: "Apple Valley, MN", code: "MN004" },
  { name: "Blaine, MN", code: "MN005" },
  { name: "Minnetonka, MN", code: "MN011" },
  { name: "Chesterfield, MO", code: "MO001" },
  { name: "Kansas City, MO - Zona Rosa", code: "MO014" },
  { name: "Bozeman, MT", code: "MT001" },
  { name: "Billings, MT", code: "MT002" },
  { name: "Charlotte, NC - Carmel", code: "NC001" },
  { name: "Charlotte, NC - Southpark", code: "NC002" },
  { name: "Raleigh, NC - Village District", code: "NC005" },
  { name: "Charlotte, NC - Rea Farms", code: "NC006" },
  { name: "Chapel Hill, NC", code: "NC007" },
  { name: "Durham, NC", code: "NC016" },
  { name: "Morrisville, NC", code: "NC020" },
  { name: "Bedford, NH", code: "NH001" },
  { name: "Marlton, NJ", code: "NJ001" },
  { name: "Lawrenceville, NJ", code: "NJ002" },
  { name: "Morristown, NJ", code: "NJ012" },
  { name: "Paramus, NJ", code: "NJ018" },
  { name: "Edgewater, NJ", code: "NJ021" },
  { name: "Shrewsbury, NJ", code: "NJ039" },
  { name: "West Caldwell, NJ", code: "NJ060" },
  { name: "Santa Fe, NM", code: "NM002" },
  { name: "Albuquerque, NM - Ventura Place", code: "NM003" },
  { name: "Henderson, NV", code: "NV001" },
  { name: "Reno, NV - Northwest", code: "NV009" },
  { name: "Las Vegas, NV - Summerlin South", code: "NV010" },
  { name: "Woodbury, NY", code: "NY001" },
  { name: "New York, NY - UES 69th", code: "NY002" },
  { name: "New York, NY - Chelsea", code: "NY003" },
  { name: "Mt. Kisco, NY", code: "NY006" },
  { name: "Brooklyn, NY - Williamsburg", code: "NY008" },
  { name: "Brooklyn - Park Slope", code: "NY010" },
  { name: "Garden City, NY - Westbury", code: "NY025" },
  { name: "New York, NY - UES 84th", code: "NY030" },
  { name: "New York, NY - UWS 76th", code: "NY031" },
  { name: "Port Chester, NY", code: "NY045" },
  { name: "Pittsford, NY", code: "NY065" },
  { name: "Eastchester, NY - Scarsdale", code: "NY069" },
  { name: "Columbus, OH", code: "OH001" },
  { name: "Westlake, OH", code: "OH002" },
  { name: "Perrysburg, OH - Levis", code: "OH003" },
  { name: "Cincinnati, OH - Hyde Park", code: "OH004" },
  { name: "Dublin, OH", code: "OH005" },
  { name: "Beavercreek, OH", code: "OH007" },
  { name: "Woodmere, OH", code: "OH010" },
  { name: "Strongsville, OH", code: "OH020" },
  { name: "Columbus, OH - Upper Arlington", code: "OH038" },
  { name: "Oklahoma City, OK - Classen Curve", code: "OK001" },
  { name: "Tulsa, OK - South", code: "OK002" },
  { name: "Lake Oswego, OR", code: "OR001" },
  { name: "Eugene, OR", code: "OR010" },
  { name: "Happy Valley, OR", code: "OR013" },
  { name: "Lancaster, PA", code: "PA001" },
  { name: "Pittsburgh, PA - Upper St. Clair", code: "PA002" },
  { name: "Plymouth Meeting, PA", code: "PA003" },
  { name: "Exton, PA", code: "PA005" },
  { name: "Pittsburgh, PA - Shadyside", code: "PA006" },
  { name: "Paoli, PA", code: "PA007" },
  { name: "Warrington, PA", code: "PA009" },
  { name: "Collegeville, PA", code: "PA011" },
  { name: "Media, PA", code: "PA016" },
  { name: "Philadelphia, PA - Center City", code: "PA019" },
  { name: "Cranberry Township, PA", code: "PA020" },
  { name: "Pittsburgh, PA - McCandless", code: "PA021" },
  { name: "Cranston, RI - Garden City", code: "RI001" },
  { name: "East Greenwich, RI", code: "RI004" },
  { name: "Charleston, SC", code: "SC001" },
  { name: "Hilton Head Island, SC", code: "SC002" },
  { name: "Greenville, SC", code: "SC003" },
  { name: "Mt Pleasant, SC - South", code: "SC004" },
  { name: "Mt Pleasant, SC - North", code: "SC012" },
  { name: "Rock Hill, SC", code: "SC013" },
  { name: "Bluffton, SC", code: "SC024" },
  { name: "Brentwood, TN", code: "TN001" },
  { name: "Nashville, TN - Green Hills", code: "TN002" },
  { name: "Nashville, TN - Music Row", code: "TN004" },
  { name: "Mt. Juliet, TN", code: "TN008" },
  { name: "Murfreesboro, TN", code: "TN018" },
  { name: "Austin, TX - Arbor Trails", code: "TX001" },
  { name: "Round Rock, TX", code: "TX002" },
  { name: "Bee Cave, TX", code: "TX003" },
  { name: "Sugar Land, TX", code: "TX004" },
  { name: "Plano, TX", code: "TX005" },
  { name: "Austin, TX - Gateway", code: "TX006" },
  { name: "Houston, TX - River Oaks", code: "TX007" },
  { name: "San Antonio, TX - Sonterra", code: "TX008" },
  { name: "Lubbock, TX", code: "TX009" },
  { name: "Austin, TX - Mueller", code: "TX010" },
  { name: "Frisco, TX - South", code: "TX011" },
  { name: "Houston, TX - West University", code: "TX012" },
  { name: "Katy, TX", code: "TX014" },
  { name: "Southlake, TX", code: "TX019" },
  { name: "San Antonio, TX - Quarry", code: "TX021" },
  { name: "Austin, TX - South Lamar", code: "TX024" },
  { name: "Dallas, TX - West Village", code: "TX025" },
  { name: "Murphy, TX", code: "TX046" },
  { name: "League City, TX", code: "TX048" },
  { name: "Irving, TX - Las Colinas", code: "TX053" },
  { name: "Cedar Park, TX", code: "TX075" },
  { name: "El Paso, TX", code: "TX079" },
  { name: "West Lake Hills, TX", code: "TX091" },
  { name: "Colleyville, TX", code: "TX095" },
  { name: "Dallas, TX - Preston Forest", code: "TX099" },
  { name: "Austin, TX - Four Points", code: "TX108" },
  { name: "College Station, TX", code: "TX112" },
  { name: "Windsong Ranch, TX", code: "TX126" },
  { name: "Draper, UT", code: "UT002" },
  { name: "Midvale, UT - Cottonwood Heights", code: "UT006" },
  { name: "Virginia Beach, VA", code: "VA001" },
  { name: "Henrico, VA - Greengate", code: "VA002" },
  { name: "Brambleton, VA", code: "VA003" },
  { name: "Midlothian, VA", code: "VA013" },
  { name: "Arlington, VA - Pentagon City", code: "VA017" },
  { name: "Vienna, VA", code: "VA026" },
  { name: "Alexandria, VA", code: "VA045" },
  { name: "Kirkland, WA", code: "WA001" },
  { name: "Issaquah, WA", code: "WA002" },
];

export const SERVICE_GROUPS = [
  "core",
  "skin-health",
  "medical",
  "weight-loss",
  "iv-drip",
];

export const AGENCIES: Agency[] = [
  { name: "Digital Tank", id: "DTMA" },
  { name: "FUEL", id: "FUEL" },
  { name: "Redefined Growth Marketing", id: "RGM" },
  { name: "Level 5 / Be Well", id: "L5" },
  { name: "Kathryn MacKinnon Business", id: "KMB" },
  { name: "Angela", id: "Angela" },
  { name: "Patient Engine", id: "PE" },
  { name: "Franchise Ramp", id: "FR" },
  { name: "Distruptive Digital (fran)", id: "DD - fran" },
  { name: "Distruptive Digital (corp)", id: "DD - corp" },
  { name: "KSAR", id: "KSAR" },
  { name: "Seminole + Clearwater", id: "seminole clearwater" },
  { name: "ROR", id: "ROR" },
];
